language: haskell
sudo: false
ghc:
  - 7.8 # Current Haskell Platform
cache:
  directories:
    - .cabal-sandbox
before_cache:
  - rm -rf .cabal-sandbox/logs .cabal-sandbox/packages
install:
  - cabal sandbox init && cabal update && cabal install cabal-install
  - export PATH=.cabal-sandbox/bin:$PATH
  - cabal --version
  - test $COMPILER = ghcjs && git clone https://github.com/ghcjs/ghcjs.git && git clone https://github.com/ghcjs/ghcjs-prim.git && cabal install --force-reinstalls  ./ghcjs ./ghcjs-prim vector && ghcjs-boot || true
  - cabal install --$COMPILER --only-dependencies --enable-tests --jobs
env:
  - PARSETS_CMD=lint COMPILER=ghc
  - PARSETS_CMD=docs COMPILER=ghc
  # - PARSETS_CMD=docs COMPILER=ghcjs
script:
  - cabal configure -fci -fdebug --$COMPILER && cabal build
  - cabal configure -fci --$COMPILER && cabal build && cabal run -- $PARSETS_CMD BlocklandGlass
notifications:
  webhooks: https://webhooks.gitter.im/e/3f5dda8eb78aa8cc9b00
