language: haskell
sudo: false
ghc:
  - 7.8 # Current Haskell Platform
install:
  - cabal install --only-dependencies --enable-tests --jobs
script:
  - cabal configure -fci -fdebug && cabal build
  - cabal configure -fci && cabal build && cabal run -- BlocklandGlass
notifications:
  webhooks: https://webhooks.gitter.im/e/3f5dda8eb78aa8cc9b00
